name: Release on Merge to Main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ensures full history
          fetch-tags: true # ensures tags are available

      - name: Get Next Version
        id: version
        run: |
          # Example: bump patch version based on last tag
          latest=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          echo "Latest tag: $latest"

          # Split version into parts
          IFS='.' read -r major minor patch <<<"${latest#v}"

          # Increment patch
          new_tag="v$major.$minor.$((patch+1))"

          echo "new_tag=$new_tag" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ steps.version.outputs.new_tag }}" \
            --target main \
            --generate-notes
